### ISSUE TITLE
Clié support

### ISSUE THREAD

**Issue by DirtyHairy** [cloudpilot-emu/cloudpilot-emu#10]
Port support for dragonball Clié devices from the Sony fork.

**Comment by Foxlum** [comment]
@DirtyHairy CXD1859GA is our ATRAC decoder (and encoder, though never used like that) of the Clie N760C and apparently does alot more too.
Some info, not a lot but some data, its more just nerdy tech hype if you get what I mean.
[atrac3_article.pdf](https://github.com/cloudpilot-emu/cloudpilot/files/7341965/atrac3_article.pdf)

**Comment by Foxlum** [comment]
I'd want to believe there is some code for it in Sony's POSE because of the amount of over reach the chip had.

**Comment by DirtyHairy** [comment]
Mostly done. Still missing:

* `NR70` & `YSX1230`: There is no emulator ROM for those, and a ROM from a real device does not run with Sony POSE. The code in Sony POSE looks pretty half-baked for those two, SZ emulation is unfinished, and there is a bunch of commented stuff in the hardware definition. Getting this to run will require some detective work.
* `S500C`: Everything's there, so that one should be trivial. Only available in Japanese though, so not exactly top priority.
* Jog wheel emulation: No technical issues, just UI.
