### ISSUE TITLE
Web build fails to load

### ISSUE THREAD

**Issue by rocheston** [cloudpilot-emu/cloudpilot-emu#20]
I built it for the web. The programs work great but ONLY if loaded like http://localhost/
But if you load in subdirectory.. http://localhost/palm then the app throws errors.

Another question: How do I open the web page with rom already configured like a config file. Instead of manually clicking  + loading ROM and starting a session. I want to type http://localhost/palm and boom the emulator loads..

![grab1](https://user-images.githubusercontent.com/16910669/153736108-39d0a45b-73d4-4218-9357-38c02807b1e4.png)
.

**Comment by DirtyHairy** [comment]
Hi rocheston!

> But if you load in subdirectory.. http://localhost/palm then the app throws errors.

That's a restriction from Angular which relies on building the base href on the server into the bundle. You can change the default by specifying `--base-href` at build time like [here](https://github.com/cloudpilot-emu/cloudpilot-emu/blob/0db98eb93073335e3ac4198488a5842dcfd4f33c/.github/workflows/deploy-githubio.yaml#L44) . There are hacks to make this dynamic, but it never has been much of a restriction for me, so I didn't care.

> Another question: How do I open the web page with rom already configured like a config file. Instead of manually clicking + loading ROM and starting a session. I want to type http://localhost/palm and boom the emulator loads.

The current UI is designed to work as a standalone app. What you really want here instead is an embeddable build that directly launches into the provided image. This request has come up before, and I created #21 for it. I am not sure yet whether I will add persistence to this, though... 🤷‍♂️ Probably not on the first run.

**Comment by rocheston** [comment]
Your solution totally worked. Thank you.
yarn build --configuration production,ci --base-href /palm/
