### ISSUE TITLE
Alarm not functioning properly on NR70V ROM

### ISSUE THREAD

**Issue by fpspad** [cloudpilot-emu/cloudpilot-emu#28]
Hi,

If you set an alarm in the calendar it won't trigger until some time later.  Can't figure out what the trigger is that will allow it to fire but it doesn't fire when it is supposed to.

Another strange alarm-based behavior is observed when you use the app TikTok. I use this app all the time to multitask.  When you set it to do a count-down timer it doesn't go off or it goes off way later than it should have.

Alarms work perfectly in other ROMs I have tested.  I would like to get it to work on the NR70V due to the extended screen available on the virtual graffiti area.

Thank you very much for your hard work on such a great emulator.  Its awesome to still use the palm pilot without carrying another device!

Frank

PS

Thank you very much for enabling sound on launch in the settings.  :)

**Comment by DirtyHairy** [comment]
Thanks for the report! I'll have to investigate, I suspect that there is some difference on the SZ w.r.t. RTC interrupt handling that is not emulated properly.

**Comment by DirtyHairy** [comment]
Fixed. Just a stupid oversight... 😏

**Comment by fpspad** [comment]
Thank you so much for the fix.  That is awesome!
