### ISSUE TITLE
No sound in Legacy on Tungsten W

### ISSUE THREAD

**Issue by gab** [cloudpilot-emu/cloudpilot-emu#37]
Hi, I tried the Legacy shareware (downloadable from redshift.hu) while emulating Tungsten W and there is no sound. I think sound is supposed to be emulated on that device?

**Comment by DirtyHairy** [comment]
Cloudpilot only supports the buildin beeper (which is all the T|W has to offer), and Legacy doesn't play sound on this. It is supposed to output audio on Clié devices (which have an additional Yamaha sound chip), but CP does not emulate that.

**Comment by gab** [comment]
Ah I see. I thought the rather basic attack sounds would've been supported on most devices. Sorry for the misleading request then, that's what happens when you don't have the original hardware on hand to check :) .
