### ISSUE TITLE
Palm standard apps not showing records in Desktop

### ISSUE THREAD

**Issue by danbae56** [cloudpilot-emu/cloudpilot-emu#40]
I mainly use Cloudpilot for running the third-party app Documents To Go, and this app and its conduit work fine, creating and updating Word documents that I can open as .doc files in Word on my computer. I recently realised, though, that the Palm Desktop app is not showing any of the records in the Date Book, Adress or Memo Pad views that I have created on the handheld, only those created in Palm Desktop itself.

When I check the files in my Palm OS Desktop/CloudpD folder on my computer, I do find text from the handheld records in e g the memopad.db file  – but oddly enough no text from the records I created on Palm Desktop. I have tried "Desktop overwrites handheld" and the other way around in HotSync Manager without success. The HotSync log says everything syncs OK. It seems Palm Desktop has lost touch with the saved databases in the CloudpD folder. Can you tell me how this can be rectified?

Session: Tungsten W 16MB RAM OS4.1
Cloudpilot for iOS, v 1.7.8, iPhone SE, iOS 16.1.1
Palm Desktop 6.2.2 running under Windows 7 on Parallels Desktop 18.1.0 installed on MacBook Pro running MacOS 12.6

**Comment by DirtyHairy** [comment]
This definitely is an issue with Palm Desktop, not with the emulator. Check https://palmdb.net/app/palm-desktop, install the hotsync fix from there and run Palm Desktop as administrator, this did the trick for 😏
