### ISSUE TITLE
Clarification: Installing Apps Using IOS

### ISSUE THREAD

**Issue by Kitsune86** [cloudpilot-emu/cloudpilot-emu#43]
I “installed” your excellent web app Palm OS emulator on my Home Screen and I was able to boot a tungsten rom successfully and the whole process was intuitive.

I’m just a little confused how to load an application onto the emulated device. The documentation says loading applications is supported but on current and preview branches the only files I’ve been able to upload are the ROM images themselves.

Is it only designed for running on a desktop with the file sync software presumably running on a VM?

iOS16
Safari
Tungsten W Image

**Comment by DirtyHairy** [comment]
You can install applications and databases straight from the emulation tab. Just tap the "Install" icon (next to the lock icon) in the toolbar --- this will allow you to select an arbitrary number of .prc and .pdb files (or zip archives containing them), and they will be installed on the device
