### ISSUE TITLE
CloudpilotServer - Null ip address

### ISSUE THREAD

**Issue by zzx-the-neptune** [cloudpilot-emu/cloudpilot-emu#46]
When i try to start the cloudpilot server i always get this:
`C:\Users\Spark\Downloads\cloudpilot-server-1.7.11>` ./cloudpilot-server serve --cert .\BananaNet.pem`
`======== Running on https://0.0.0.0:8667 ========`
`(Press CTRL+C to quit)`
Why is this happening?

**Comment by DirtyHairy** [comment]
This is perfectly normal. `0.0.0.0` just means that the server is listening on all network interfaces.
