### ISSUE TITLE
cloudpilot-server generate-cert

### ISSUE THREAD

**Issue by stumiller3** [cloudpilot-emu/cloudpilot-emu#51]
Hi, any help appreciated as I'm not that familiar yet with terminal commands...

Server downloaded and extracted to /tmp, then trying...

stumiller3@raspberrypi:/tmp/cloudpilot-server-1.8.1 $ cloudpilot-server generate-cert
result;
bash: cloudpilot-server: command not found

Emu on IOS running fine, was hoping to hotsync to Palm Desktop on Win 7 laptop.

**Comment by DirtyHairy** [comment]
You need to qualify the executable with a path, i.e.

```
     stumiller3@raspberrypi:/tmp/cloudpilot-server-1.8.1 $ ./cloudpilot-server generate-cert
```

**Comment by stumiller3** [comment]
Tried that previously, but clearly I must be doing something wrong...

stumiller3@raspberrypi:/tmp/cloudpilot-server-1.8.1 $ ./cloudpilot-server generate-cert
bash: ./cloudpilot-server: cannot execute binary file: Exec format error

I thought this may be due to base_library.zip not being extracted, so I did that, but then got

stumiller3@raspberrypi:/tmp/cloudpilot-server-1.8.1 $ ./cloudpilot-server generate-cert
bash: ./cloudpilot-server: No such file or directory

**Comment by DirtyHairy** [comment]
Nah, you are not expected to extract any of the files in that folder. However, I just notice that you are running on a raspberry pi, that's ARM --- it cannot execute the packaged version of the server, which is built for x86-64.

You either have to run the server on a x86-64 machine, or you have to check out the repository and [run it from source](https://github.com/cloudpilot-emu/cloudpilot-emu/blob/master/doc/networking.md#running-the-server-from-git) on your pi. The latter is not hard to do, I can assist you if necessary.

**Comment by stumiller3** [comment]
Tried the server on 64 bit laptop, I'm guessing here but does it need Python 3.9? I can only run 3.7 on Win 7...

C:\Users\Stuart\Downloads\cloudpilot\cloudpilot-server-1.8.1-win-x64\cloudpilot-
server-1.8.1>server-1.8.1>cloudpilot-server generate-cert

gives

Error loading Python DLL 'C:\Users\Stuart\Downloads\cloudpilot\cloudpilot-server
-1.8.1-win-x64\cloudpilot-server-1.8.1\python39.dll'.

**Comment by DirtyHairy** [comment]
Ah, sorry, I forgot to respond. Yeah, newer versions of Python require windows 8 or better. You should be able to run the server from source with an older version of python, though.
