### ISSUE TITLE
Building cloudpilot-server on Termux

### ISSUE THREAD

**Issue by MaxWell-775** [cloudpilot-emu/cloudpilot-emu#52]
I want to ask how to build cloudpilot-server on Termux?

**Comment by DirtyHairy** [comment]
An interesting experiment 😏 There is no need to build the server, it just a Python application, so you need to install a recent python in termux. If you can get `pipenv` set up in termux, then you can just do `pipenv install` in `cloudpilot/server` to install the dependencies, and `pipenv run cloudpilot-server` to run it. If you can't get pipenv running you still can just install the dependencies using `pip` and run `cloudpilot-server.py` directly.

The only potential issue that I can see is my dependency on `pyopenssl` (which includes native code), the rest should be pure python 🤷‍♂️ If you have issues getting `pyopenssl` running, then you can modify `cloudpilot-server.py` to get rid of `generate-cert` --- this is the only place where I actually use it.

Good luck, and tell me how it goes.

**Comment by romanovj** [comment]
clang and rust shoud be enough for installing server
pip install pipenv
cd cloudpilot-emu/server
pipenv install
![Uploading Screenshot_20230725-201036_Termux.png…]()

**Comment by MaxWell-775** [comment]
DirtyHairy, Well, for me, this is not an experiment. My computer broke down, and it's very old as well.
I installed pipenv following romanovj's advice, but when I run "pipenv install," it gives the appearance of working, but then it starts showing errors mentioning "--hash=sha256," and eventually, it stops working and displays a log.
Apologies for the inconvenient long screenshots, but I just want to show what happened.
![Screenshot_20230726-011555672.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/8edcccd9-2e40-4765-8700-f4c5b3e98410)

![Screenshot_20230726-011513039.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/4b62f13b-fa25-4683-8d85-7ebe84fc5f11)

![Screenshot_20230726-011605193.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/d4a644d0-007e-4c25-88cb-8b1a8cedff74)

![Screenshot_20230726-011534823.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/fe5b5373-c562-40a1-890b-996a77f46c93)

**Comment by MaxWell-775** [comment]
DirtyHairy, Well, for me, this is not an experiment. My computer broke down, and it's very old as well.
I installed pipenv following romanovj advice, but when I run "pipenv install," it gives the appearance of working, but then it starts showing errors mentioning "--hash=sha256," and eventually, it stops working and displays a log.
Apologies for the inconvenient long screenshots, but I just want to show what happened.
![Screenshot_20230726-011513039.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/0d805a95-2337-4287-a2f7-42e7da038346)

![Screenshot_20230726-011534823.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/dda0ad2e-f7f3-435d-8a6d-b35fa2de2d6c)

![Screenshot_20230726-011555672.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/81e239f3-88b7-4ab3-a60f-571202991bcd)

![Screenshot_20230726-011605193.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/89449a20-be85-459d-9178-13e42ddf0521)

**Comment by MaxWell-775** [comment]
romanovj, Thank you for the detailed advice on how to install and set up pipenv, but unfortunately, it didn't help me. I have explained the reason above.

**Comment by romanovj** [comment]
@MaxWell-775 
pkg install python make rust libcrypt libffi llvm binutils-is-llvm libandroid-execinfo -y

pip install wheel
pip install setuptools
pip install aiohttp_cors==0.7.0
export 
CARGO_BUILD_TARGET="$(rustc -Vv | grep "host" | awk '{print $2}')"

pipenv install

**Comment by MaxWell-775** [comment]
@romanovj, thank you for your help. Following your instructions, I successfully set up pipenv for cloudpilot-server and managed to run it successfully. Thank you again.

**Comment by MaxWell-775** [comment]
@DirtyHairy, Hello, at the end of your post, you inquired about how things are going with me. Following romanovj's instructions, I set up pipenv and successfully launched cloudpilot-server. Here are the screenshots (taken in the web browser PocketLink v2.56c):
![Screenshot_20230726-143058836.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/24213208-19f0-4a1b-9f0c-f3360e274a2c)

![Screenshot_20230726-143223071~2.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/a55b4ff3-6b0a-44d8-9e4e-d121e48a616f)

![Screenshot_20230726-143438919.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/db9e81af-1665-42bc-92ff-f3556ad59646)

![Screenshot_20230726-143505658.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/91a60d86-20ec-4490-835c-9a73c2f6a75b)

![Screenshot_20230726-143547639.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/89f8f057-1e59-4613-b500-081fc453956c)

![Screenshot_20230726-143602464.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/fcb54f90-dc28-4ce7-b0e1-46f9cb7610b3)

![Screenshot_20230726-143947365.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/fa888ae5-c328-4312-aea4-7cf75a2471b1)



On the second tab of the session, I launched the OpenXiino dataserver for the Xiino web browser.
Result:
![Screenshot_20230726-144602096.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/682df92a-22c0-46d9-9842-e447661a98e8)

![Screenshot_20230726-144703131~2.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/94dcce21-7706-42d0-b1ed-16f68d126118)

![Screenshot_20230726-144813321.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/4e0ee903-d7ae-4629-9411-536421095116)

![Screenshot_20230726-144838051.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/0aa6be35-51a8-4fe0-8dea-b10ae46e80e8)

![Screenshot_20230726-144905325.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/0c2be374-bcae-454c-9dbe-2728201dd520)

![Screenshot_20230726-144933007.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/026cd38f-ff44-4398-a3a1-3bf6398f72af)

![Screenshot_20230726-145031582.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/96a84ca8-ad7e-459d-9721-93ce2ca9c57d)

![Screenshot_20230726-145046848.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/29a2c3cc-ad71-41fc-8f81-e632144435ff)

![Screenshot_20230726-145109777.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/c2d29de8-5e2c-433d-b46b-399f6b35696e)

![Screenshot_20230726-145116988.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/3e2e7930-dd48-46db-9c1d-22f77ce43c26)

![Screenshot_20230726-145135014.jpg](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/75186533/a598f3fd-9416-4c2f-9ac5-ddbefac37599)

**Comment by DirtyHairy** [comment]
So you can get connectivity on an Android phone without a second machine that runs the server. Nice! Thanks for sharing your success....
