### ISSUE TITLE
Hotsync issue

### ISSUE THREAD

**Issue by YT-PC** [cloudpilot-emu/cloudpilot-emu#54]
I am trying to setup Hotsync with Cloudpilot and can't generate a certificate. When I click on cloudpilot-server.exe, Windows CMD window opens up then immediately closes. I've tried on my desktop and laptop with same results. Windows 11 both computers and tried server 1.8.1 and 1.8.0 same results... any help appreciated!

**Comment by DirtyHairy** [comment]
The server is a terminal program; you must run it from Powershell or cmd.
