### ISSUE TITLE
Clipboard Integration Not Working

### ISSUE THREAD

**Issue by fpspad** [cloudpilot-emu/cloudpilot-emu#56]
Hi,

Im using the sony NR70v emulator and clipboard integration is not working.  I was able to paste text to google keep but when I attempt to perform a paste to the palm it freezes up and I need to do a reset to get it to come back.

Please advise.

Thanks.

Frank

**Comment by fpspad** [comment]
Doing some further testing, I was unable to copy and paste from within cloutpilot iteself.

I am running cloudpilot on a samsung ultra23.

**Comment by DirtyHairy** [comment]
Hi @fpspad !

Pasting to a memo works reliably for me with a NR70 image. What browser are you using? What PalmOS app are you pasting to? What is the content of your clipboard? Can you check with a different content and a memo?

**Comment by DirtyHairy** [comment]
What do you mean by "from within Cloudpilot itself"? Deactivating clipboard integration fully bypasses CPs clipboard handling and just leaves this up to Cloudpilot --- there is no way this can fail, short of an OS bug. If you say that you cannot copy and paste in this fashion, could you provide me with a session image?

**Comment by fpspad** [comment]
Hi Christian , I am running Chrome on my Android s23 ultra. I went into the memo app and typed the word test. I highlighted the word and copied it. I went down another line and attempted the paste it and it froze. I have to do a reset normal boot to get cloud pilot to operate again. Thank you very much for looking into this.FrankSent from my Galaxy
-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/19/23  11:57 AM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
Hi @fpspad !
Pasting to a memo works reliably for me with a NR70 image. What browser are you using? What PalmOS app are you pasting to? What is the content of your clipboard? Can you check with a different content and a memo?

**Comment by DirtyHairy** [comment]
I see. Does this happen with "Clipboard Integration" turned on or turned off? Can you save a session image and send it to me (unless this contains sensitive data, of course)?

**Comment by fpspad** [comment]
First attempt to send this to you failed because the image file was too big.  Here is a link to the file from my dropbox account.Thank you again for looking into this.Frankhttps://www.dropbox.com/scl/fi/x7j983p9pua6dktkpfay9/Sony-Clie-NR70v.rom-230727-1-_20230919-160017.bin?rlkey=98vm0n9blwefg65adn93fzqxs&dl=0Sent from my Galaxy
-------- Original message --------From: pezdel ***@***.***> Date: 9/19/23  4:01 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***>, cloudpilot-emu/cloudpilot-emu ***@***.***>, ***@***.*** Cc: Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) Hi Christian,I turned clipboard integration off and paste still crashed it.  I highlighted the word test and attempted to paste it below on the next line. This failed with clipboard integration on and off.  Originally I thought the problem was with clipboard integration because I was attempting to paste from my pc (i use a samsung ultra 23 with DEX integration).Attached is the session image.Thank you so much for looking into this.FrankSent from my Galaxy-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/19/23  1:24 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
What do you mean by "from within Cloudpilot itself"? Deactivating clipboard integration fully bypasses CPs clipboard handling and just leaves this up to Cloudpilot --- there is no way this can fail, short of an OS bug. If you say that you cannot copy and paste in this fashion, could you provide me with a session image?

**Comment by fpspad** [comment]
Hi Christian,Here is a dropbox link to the session image.Original problem was discovered from attempting clipboard integration.  I later tried to do it within cloudpilot itself and still had problems.Thank you so much for looking into this.For the record I use a samsung ultra 23 and also use it with DEX integration on my desktop.I attempted to also send this to you earlier but it failed due to the size of the image file.  You may get a response twice. The link is to the same image file.Frankhttps://www.dropbox.com/scl/fi/x7j983p9pua6dktkpfay9/Sony-Clie-NR70v.rom-230727-1-_20230919-160017.bin?rlkey=98vm0n9blwefg65adn93fzqxs&dl=0Sent from my Galaxy
-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/19/23  1:24 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
What do you mean by "from within Cloudpilot itself"? Deactivating clipboard integration fully bypasses CPs clipboard handling and just leaves this up to Cloudpilot --- there is no way this can fail, short of an OS bug. If you say that you cannot copy and paste in this fashion, could you provide me with a session image?

**Comment by DirtyHairy** [comment]
Hi Frank!

Thanks for the session files. Unfortunately, I cannot reproduce the issue with those either, neither on my Mac, nor on the Android emulator. Copying and pasting in memos --- both with and without clipboard integration --- works fine for me.

What exactly does "lock up" mean? Does the app (Cloudpilot) still work, and do you have to reset the virtual device, or is it Cloudpilot that requires a reload?

A remote possibility (although this wouldn't explain crashing): did you accidentally deny permission for clipboard access when asked? You can check the website permissions in the Chrome settings, and  if you accidentally denied permission, you change that choice there, too.

Cheers
    -Christian

**Comment by fpspad** [comment]
Ok, after playing with some permissions i got copy/paste to work from within the cloudpilot emulator.Now when I turn on clipboard integration I am getting the below error message.  How do I fix this?Sent from my Galaxy
-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/19/23  5:14 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
Hi Frank!
Thanks for the session files. Unfortunately, I cannot reproduce the issue with those either, neither on my Mac, nor on the Android emulator. Copying and pasting in memos --- both with and without clipboard integration --- works fine for me.
What exactly does "lock up" mean? Does the app (Cloudpilot) still work, and do you have to reset the virtual device, or is it Cloudpilot that requires a reload?
A remote possibility (although this wouldn't explain crashing): did you accidentally deny permission for clipboard access when asked? You can check the website permissions in the Chrome settings, and  if you accidentally denied permission, you change that choice there, too.
Cheers
-Christian

**Comment by fpspad** [comment]
Nevermind.  I figured it out. Apparently you have to give each site approval and I had to give cloudpilot specific approval for pasting in Chrome.  I never knew that existed.Thanks.FrankSent from my Galaxy
-------- Original message --------From: pezdel ***@***.***> Date: 9/19/23  5:37 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***>, cloudpilot-emu/cloudpilot-emu ***@***.***>, ***@***.*** Cc: Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) Ok, after playing with some permissions i got copy/paste to work from within the cloudpilot emulator.Now when I turn on clipboard integration I am getting the below error message.  How do I fix this?Sent from my Galaxy-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/19/23  5:14 PM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
Hi Frank!
Thanks for the session files. Unfortunately, I cannot reproduce the issue with those either, neither on my Mac, nor on the Android emulator. Copying and pasting in memos --- both with and without clipboard integration --- works fine for me.
What exactly does "lock up" mean? Does the app (Cloudpilot) still work, and do you have to reset the virtual device, or is it Cloudpilot that requires a reload?
A remote possibility (although this wouldn't explain crashing): did you accidentally deny permission for clipboard access when asked? You can check the website permissions in the Chrome settings, and  if you accidentally denied permission, you change that choice there, too.
Cheers
-Christian

**Comment by fpspad** [comment]
When I finally saw the setting in chrome for clipboard access it said it was set to ask every time. However it never asked. When I turned it off and on then it reset and asked. Then cloud pilot showed up in the list and I was able to grant it access. Perhaps the browser state was a little screwy because I migrated from an old Samsung to a new Samsung recently using their smart switch application and the setting didn't migrate over cleanly. Idk. Very glad to have it working. Now I wish there were a way to have it keep running in the background so I could get alerts without having to have it be in the foreground. I have tried the feature on Samsung that allows you to keep an app from closing but it doesn't help. I guess it's not technically possible. Is there a chance that cloud pilot could be written as an android app so the alerts could work?Sent from my Galaxy
-------- Original message --------From: Christian Speckner ***@***.***> Date: 9/20/23  11:39 AM  (GMT-05:00) To: cloudpilot-emu/cloudpilot-emu ***@***.***> Cc: fpspad ***@***.***>, Mention ***@***.***> Subject: Re: [cloudpilot-emu/cloudpilot-emu] Clipboard Integration Not Working
  (Issue #56) 
Glad to hear your problem is solved. I still am a bit mystified by what exactly happened on your end. Usually, Chrome asks whether you want to grant clipboard access on first use. Only if you denied this you have to reenable it.
Another weird things are the "lockups" you describe. If clipboard integration is disabled, CP does not interfere with the clipboard at all, and the browser permissions are irrelevant. CP will access the browser clipboard API only if integration is enabled, and in this case pasting without permission will cause an error dialog, not a lockup. Copying on Android (at least vanilla) is not affected by the permission setting and will always work.
So, I still have no coherent explanation for your issue, but at least it is solved 🤷‍♂️
