### ISSUE TITLE
Problems building native app

### ISSUE THREAD

**Issue by therion23** [cloudpilot-emu/cloudpilot-emu#60]
Hello,

Two issues i came across while "make bin" (Debian x86_64, gcc 13.2):

1) common/ZipfileWalker and vfs/ZipfileIterator both break the build, suggesting i add #include <cstdlib> - which i did, and build commenced.

2) This one is more tricky:

```
mkdir -p .build/emulator/patch/ && mkdir -p .deps/emulator/patch/ && g++ -MT .build/emulator/patch/EmPatchMgr.o -MMD -MP -MF .deps/emulator/patch/EmPatchMgr.d -Werror -Wextra -Wall -Wno-unused-parameter -Wno-pragma-pack -Wno-multichar -Wno-unknown-pragmas -Wno-missing-field-initializers -DEMULATION_LEVEL=EMULATION_UNIX -std=c++17 -DENABLE_DEBUGGER -O2  -g -I/usr/include/SDL2 -D_REENTRANT -I../common -I../common/zip -I../skins -I./emulator/hardware -I./emulator/hardware/clie -I./emulator/hardware/handera -I./emulator/hardware/acer -I./emulator/uae -I./emulator/patch -I./emulator/patch/clie -I./emulator/savestate -I./emulator/palm/Device -I./emulator/palm/Platform -I./emulator/palm/Platform/Core/Hardware/IncsPrv -I./emulator/palm/Platform/Core/System/IncsPrv -I./emulator/palm/Platform/Incs -I./emulator/palm/Platform/Incs/Core -I./emulator/palm/Platform/Incs/Core/Hardware -I./emulator/palm/Platform/Incs/Core/System -I./emulator/palm/Platform/Incs/Core/UI -I./emulator/palm/Platform/Incs/Libraries -I./emulator/suspend -I./emulator -I./nanopb -I./proto  -I../argparse -c -o .build/emulator/patch/EmPatchMgr.o emulator/patch/EmPatchMgr.cpp
In function ‘void {anonymous}::DoSaveLoad(T&, TailpatchType&) [with T = SaveChunkHelper<ChunkProbe>]’,
    inlined from ‘static void EmPatchMgr::Save(T&) [with T = SavestateProbe]’ at emulator/patch/EmPatchMgr.cpp:191:23:
emulator/patch/EmPatchMgr.cpp:76:27: error: ‘filler.TailpatchType::fCount’ may be used uninitialized [-Werror=maybe-uninitialized]
   76 |         helper.Do32(patch.fCount);
      |                     ~~~~~~^~~~~~
emulator/patch/EmPatchMgr.cpp: In static member function ‘static void EmPatchMgr::Save(T&) [with T = SavestateProbe]’:
emulator/patch/EmPatchMgr.cpp:186:23: note: ‘filler’ declared here
  186 |         TailpatchType filler;
      |                       ^~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-pragma-pack’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:354: .build/emulator/patch/EmPatchMgr.o] Error 1
```
Removing -Werror from src/cloudpilot/Makefile lets me finish the build, and the end product seems to work just fine. There might, of course, be similar errors later on in the build process.

I know next to nothing about C++, so bear with me if the above makes little sense.

Happy easter!

**Comment by DirtyHairy** [comment]
Hi @therion23 !

Thanks for the pointer, I've fixed the build. One of those days I'll set up a GH build action to catch those a little earlier --- I am developing on MacOS with LLVM which is more lenient compared to gcc 😏

**Comment by DirtyHairy** [comment]
... and added a GH action to make sure that the Linux build does not break without me noticing again.

**Comment by therion23** [comment]
Sounds excellent - tell me when i can do a pull and test it, will gladly help out running a build or ten until it works.

**Comment by DirtyHairy** [comment]
The build is fixed, you should be able to pull and build just fine now.

**Comment by therion23** [comment]
I get this:

mkdir -p .build/emulator/ && mkdir -p .deps/emulator/ && g++ -MT .build/emulator/MemoryRegion.o -MMD -MP -MF .deps/emulator/MemoryRegion.d -Werror -Wextra -Wall -Wno-unused-parameter -Wno-pragma-pack -Wno-multichar -Wno-unknown-pragmas -Wno-missing-field-initializers -DEMULATION_LEVEL=EMULATION_UNIX -std=c++17 -DENABLE_DEBUGGER -O2  -g -I/usr/include/SDL2 -D_REENTRANT -I../common -I../common/zip -I../skins -I./emulator/hardware -I./emulator/hardware/clie -I./emulator/hardware/handera -I./emulator/hardware/acer -I./emulator/uae -I./emulator/patch -I./emulator/patch/clie -I./emulator/savestate -I./emulator/palm/Device -I./emulator/palm/Platform -I./emulator/palm/Platform/Core/Hardware/IncsPrv -I./emulator/palm/Platform/Core/System/IncsPrv -I./emulator/palm/Platform/Incs -I./emulator/palm/Platform/Incs/Core -I./emulator/palm/Platform/Incs/Core/Hardware -I./emulator/palm/Platform/Incs/Core/System -I./emulator/palm/Platform/Incs/Core/UI -I./emulator/palm/Platform/Incs/Libraries -I./emulator/suspend -I./emulator -I./nanopb -I./proto  -I../argparse -c -o .build/emulator/MemoryRegion.o emulator/MemoryRegion.cpp
In file included from emulator/MemoryRegion.h:4,
                 from emulator/MemoryRegion.cpp:1:
In member function ‘constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = unsigned int; long unsigned int _Nm = 6’,
    inlined from ‘void MemoryRegionMap::AllocateRegion(MemoryRegion, uint32)’ at emulator/MemoryRegion.cpp:10:5:
/usr/include/c++/13/array:203:24: error: array subscript 6 is above array bounds of ‘std::__array_traits<unsigned int, 6>::_Type’ {aka ‘unsigned int [6]’} [-Werror=array-bounds=]
  203 |         return _M_elems[__n];
      |                ~~~~~~~~^
/usr/include/c++/13/array: In member function ‘void MemoryRegionMap::AllocateRegion(MemoryRegion, uint32)’:
/usr/include/c++/13/array:109:55: note: while referencing ‘std::array<unsigned int, 6>::_M_elems’
  109 |       typename __array_traits<_Tp, _Nm>::_Type        _M_elems;
      |                                                       ^~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-pragma-pack’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors

**Comment by DirtyHairy** [comment]
Ouch, you're right, I should have checked what GCC is used by the github runner 😏 GCC 13 seems to be paranoid about array bounds. Please pull and build again, I've now tested against GCC 13.

**Comment by therion23** [comment]
Now it looks clean from a gcc 13.2 view. Good job, and of course thank you!

**Comment by DirtyHairy** [comment]
👍 You're welcome, have a happy easter!
