### ISSUE TITLE
Change the serial number

### ISSUE THREAD

**Issue by TheRed9999** [cloudpilot-emu/cloudpilot-emu#62]
Can I change the Palm serial number so that all the app licenses that worked on the hardware Palm will work on the emulated Palm ?

**Comment by DirtyHairy** [comment]
PalmOS apps usually use the Hotsync user name to generate codes, and you can set that in the session options.

**Comment by TheRed9999** [comment]
I already set the user name the same but the serial number of the emulated Palm is different for my hardware Palm. Thanks for the suggestion anyway.

**Comment by DirtyHairy** [comment]
Are you referring to the ROM serial number (as described [here](https://www.fuw.edu.pl/~michalj/palmos/SystemFeatures.html#925728))? I don't currently support overriding this, but it would be trivial to add such a feature. Tbh I have never encountered an app that ties its registration to this number, and it is only available on flash units.

Is this the number that you refer to?

**Comment by DirtyHairy** [comment]
BTW, if you dump your hardware Palm's ROM (i.e. with pilot-link) and use that the serial will transfer, too, it is part of the ROM.

**Comment by DirtyHairy** [comment]
Also, another suggestion: [MultiUserHack](https://palmdb.net/app/multiuserhack) allows you to override the serial on a per-app basis.

**Comment by TheRed9999** [comment]
The serial number is in the form in the attached file and repeated here “igmz-id26”. This is generated by the emulator.
I forgot to thank for the great work of this emulator. All my palm hardware devices
![0CF3F55C-18C5-442F-8AE4-E7481E6A9A6E](https://github.com/cloudpilot-emu/cloudpilot-emu/assets/170175840/bdcf1f81-236d-4377-93d6-b907af71b768)
 died and the emulator has come to the rescue. Thank you so much ! I also managed to read the whole backup DB file into the emulator with zero error. That’s just amazing !

**Comment by DirtyHairy** [comment]
Thanks for your kind words 😏 Also, thanks for the screenshots, now I see what you are referring to. This "SerNo" is nothing that is reported by PalmOS (or by the emulator), but it is just some code calculated by SuperMemo from other quantities. From a bit of experimenting I think it is derived solely from the hotsync user name --- it does not change when I modify the ROM serial using multiuser hack, and it matches between a virtual m515, a virtual Vx and a virtual T675 if the user name is set to the same value.

Can you doublecheck that you set the same hotsync user that was set on your real palm from when you registered the app?

**Comment by TheRed9999** [comment]
Wow it worked ! All that I have changed is the upper case of two letters of my user name. Thanks for your great help ! Now my emulator is working perfectly !

**Comment by DirtyHairy** [comment]
Nice! Have fun... 😏
