### ISSUE TITLE
No contact with proxy server

### ISSUE THREAD

**Issue by danbae56** [cloudpilot-emu/cloudpilot-emu#65]
Hi,

I have previously managed to set up a proxy server for my Cloudpilot, such that I can run HotSync with Palm Desktop. Now I have moved to a new flat, and when I try to make the setup once again, there is no connection to the proxy server. The following steps work without problem:

1. Downloading Cloudpilot Server
2. Generating the certificate
3. Installing the certificate on my phone
4. Launching the proxy server

However, when I test the connection to the proxy server from Cloudpilot's Host Integration settings, I get en error message: "unable to connect to proxy". When I try to navigate to the server via a web browser (Safari) on my phone, I get the error message "Unable to open page since the network connection was lost."

I have tried to fiddle with the firewall settings for my new router, making them more permissive, but without success. Could you please suggest further diagnostics or manipulations? Is there any question I could ask my ISP about firewalls etc?

I have really become dependent on having Cloudpilot and Cloudpilot Server working for me, so I would very much appreciate any help.

Best,
Dan Baeckström

Cloudpilot Server v 1.10.2
OS: MacOS 12.7.5
Computer: MacBook Pro (Retina, 13-inch, Early 2015)

Cloudpilot v 1.10.2
iOS: 17.5.1
Phone: iPhone SE

**Comment by tatbestand216** [comment]
Have you checked TCP/IP of palmdesketop?

**Comment by danbae56** [comment]
As far as I can understand this, Palm Desktop is not a part of the problem, at least not yet :) 
The issue is, my Cloudpilot can't access the proxy server (using the "Test" button, see image). I don't have to have Palm Desktop up and running in order to establish a connection between Cloudpilot and the proxy server – unless I have misunderstood the whole thing. Palm Desktop gets involved once I have a working connection to the proxy server and then try to do HotSync. 
![image](https://github.com/user-attachments/assets/249d63b1-54a4-415c-924d-b5b3e02ca316)

**Comment by DirtyHairy** [comment]
Mmh, hard to say what's going on. What are the IP addresses involved (of the machine that runs the proxy server and of the client)? Do you have any firewall rules active on your router? Is the MacOS Firewall enabled?

**Comment by danbae56** [comment]
The Mac that runs the proxy server has the IP address 192.168.1.152 and my iPhone which runs Cloudpilot has IP # 192.168.1.86. There were no visible active firewall rules when I started troubleshooting. I have then tried to add some, but without success. The router admin panel says its default policy for incoming packets is DROP. I have not tried fiddling with DSCP settings as I have no idea what DSCP is. 

The MacOS firewall is disabled. All the settings for Cloudpilot and the proxy server (except the host IP address) are the same as in my previous flat. The obvious thing that differs is the router. It is also connected to another ISP than in my old flat.

**Comment by DirtyHairy** [comment]
Sorry for asking the obvious, but what happens on your iPhone if you access `http://192.168.1.152:8666` and `https://192.168.1.152:8667`? I suppose those IP addresses changed when you migrated to your new setup? Did you create a new certificate that includes the correct IPs (they are encoded in the certificates subjectaltname, and one has to match the server)?

**Comment by danbae56** [comment]
Typing http://192.168.1.152:8666 and https://192.168.1.152:8667 into Safari on my iPhone gives the following results: 
For port 8666, Safari said "Safari can't open the page. The error was: The URL can't be shown".
For port 8667, Safari said "Unable to open the page because the network connection was lost."
(note: the error messages are translated from Swedish).
Interestingly, the error messages differed depending on the port.

I did enter the proxy server host IP 192.168.1.152 in the new certificate I generated after moving to my new flat. I also made new certificates a few times to exclude the risk of mistyping the address. However, the term "subjectaltname" is unknown to me. Anyway, I followed the same procedure as in my old flat, just with another host IP number.

The proxy server's startup message is "======== Running on https://0.0.0.0:8667 ========", but I seem to remember that it is the same as earlier.

**Comment by DirtyHairy** [comment]
Can you check whether you can access the same URLs on your Mac?

**Comment by DirtyHairy** [comment]
Oh, and can you post the swedish originals? I don't speak swedish, but maybe google turns up something useful about the underlying reason 😏

**Comment by DirtyHairy** [comment]
And another question: what router are you using in your new flat?

**Comment by danbae56** [comment]
Here are the error messages from Chrome on my Mac. 

For port 8666:
![image](https://github.com/user-attachments/assets/9bbec152-45f3-468f-8eca-f4fda0d9fa74)

And for port 8667:
![image](https://github.com/user-attachments/assets/47e12c62-8c00-47e3-b432-79f269880b26)

And here is the screen dump from Safari for port 8666 (this time, it said: "Safari could not open the page since the server could not be reached"
![IMG_7894](https://github.com/user-attachments/assets/6d655278-6f24-4c99-b020-77fdfa244026)

And the corresponding one for port 8667, using http (you had specified https here, but that only directed me to a warning message "Your connection is not secure"): 
![IMG_7895](https://github.com/user-attachments/assets/65e728ab-593a-4114-9239-e26b1a0c8024)
.

The router is branded by the ISP, but the manufacturer seems to be Technicolor Delivery Technologies. I can send you an image of the backside label on a private channel, if it helps.

And one more thing: the housing association that this flat belongs to has a collective internet subscription with the ISP, although each flat has its own router.

**Comment by DirtyHairy** [comment]
This is good, so the server is accessible as far as the network is concerned. Did you have to confirm the security warning on iOS? This means that the root certificate has not been properly imported on your phone. If you navigate to Settings -> General -> About -> Certificate Trust settings, is your new root certificate listed and activated?

**Comment by danbae56** [comment]
Yes, I got the security warning also on my iPhone browser. You are also right that the certificate was not activated. When I asked to activate it, I got a warning message "If you activate this certificate for websites, third parties can see all private data that you send to websites". When I confirmed activation, Cloudpilot could indeed access the proxy server. Thank you very much!! I did not have to go through these extra steps with the network in my old flat, so I didn't expect them to be there :) 
I guess I can ignore the warning message I got when I activated the cert?

**Comment by DirtyHairy** [comment]
🎉  You can indeed ignore the warning. If you install a root certificate, you are implicitly trusting all certificates that were signed with this root, and an attacker can use that to attack secure connections by exchanging certificates with forged ones that will allow them to decrypt the communication, so in general that warning should be taken seriously.

However, with CloudpilotEmu, I use the generated root certificate to sign the certificate used by the server and then immediately erase the key, so no further certificates can be signed with this root, so installing it does not pose a security risk

**Comment by danbae56** [comment]
Terribly sorry to bother you again. Although the connection between the emulator and the proxy server can be established now, HotSync fails. The proxy server says:
```
cloudpilot-server:INFO: 2024-08-21 09:19:43,079: starting proxy connection 2
cloudpilot-server:WARNING: 2024-08-21 09:19:48,245: failed to send: PermissionError: [Errno 13] Permission denied
cloudpilot-server:WARNING: 2024-08-21 09:19:48,255: failed to send: PermissionError: [Errno 13] Permission denied
cloudpilot-server:WARNING: 2024-08-21 09:19:48,265: failed to send: PermissionError: [Errno 13] Permission denied
cloudpilot-server:WARNING: 2024-08-21 09:19:53,356: failed to resolve host DAN3321: gaierror: [Errno 8] nodename nor servname provided, or not known
cloudpilot-server:INFO: 2024-08-21 09:19:53,379: connection 2 closed
```
My setup for Palm Desktop is such that it runs in a Windows 7 environment emulated on my Mac using Parallels Desktop. This has worked earlier. I have now tried both the "Shared", "Host-only", and "Bridged > Wifi" network options in Parallels, without success (the latter option was previously used successfully). 
Using Windows' Command Interpreter's `ipconfig/all` command, I have established that the hostname DAN3321 is correct and I have entered the IPv4 address provided by the interpreter into HotSync's Primary PC Setup field. Do you have any suggestions for diagnosing or rectifying this?

Palm Desktop 6.2.2
Windows 7 Professional
Parallels Desktop 18.3.2

**Comment by DirtyHairy** [comment]
Can you rerun the server with `--log debug`? What is the IP that you are entering in PalmOS?

All three networking modes will work, but you have to adapt the IP that you enter in PalmOS accordingly. I **think** what happens is that the IP is wrong and the hostname cannot be resolved via DNS. You can leave the name empty in PalmOS, it is not required, IP and netmask are enough.

**Comment by danbae56** [comment]
The IP address and subnet mask I am entering into the HotSync settings for PC setup is the one shown by the ipconfig/all command in Windows:
![image](https://github.com/user-attachments/assets/29dc8e14-003a-4615-825e-51e5e2d3580c)
![IMG_7898](https://github.com/user-attachments/assets/f4faa112-9e6c-4ba8-a807-55d4ec528d76)

It will be different depending on Parallels' networking mode, but I always check that it matches the `Primary PC Adress` in HotSync.

Rerunning the server in -`-log debug` mode gives the following printout when I attempt to do HotSync:

```
======== Running on https://0.0.0.0:8667 ========
(Press CTRL+C to quit)
cloudpilot-server:INFO: 2024-08-21 12:24:21,982: issued token, lifetime 10 seconds
cloudpilot-server:INFO: 2024-08-21 12:24:22,033: starting proxy connection 0
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,113: socketOpenRequest: type=1 protocol=0
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,127: socketOptionSet handle=1 level=65535 option=8192 value=1 timeout=2000
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,135: socketAddrRequest: handle=1 requestAddressLocal=True requestAddressRemote=False timeout=-1
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,143: socketBindRequest: handle=1 address=('0.0.0.0', 0) timeout=-1
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,151: socketOpenRequest: type=2 protocol=0
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,162: socketOptionSet handle=2 level=65535 option=8192 value=1 timeout=2000
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,171: socketConnectRequest handle=1 address=('192.168.1.184', 14238) timeout=90000
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,179: select width=2 readFDs=[] writeFDs=[1] exceptFDs=[1] timeout=500
cloudpilot-server:DEBUG: 2024-08-21 12:24:22,766: select width=2 readFDs=[] writeFDs=[1] exceptFDs=[1] timeout=500
cloudpilot-server:DEBUG: 2024-08-21 12:24:23,380: select width=2 readFDs=[] writeFDs=[1] exceptFDs=[1] timeout=500
cloudpilot-server:DEBUG: 2024-08-21 12:24:23,997: select width=2 readFDs=[] writeFDs=[1] exceptFDs=[1] timeout=500
```
the last line repeats until I reset Cloudpilot, whereupon the server says:

`cloudpilot-server:INFO: 2024-08-21 12:24:44,161: connection 0 closed`

**Comment by DirtyHairy** [comment]
OK, I haven't hotsynced for a while, so I retried myself 😏 The good news: it still works for me with a similar setup (Parallels / Win 11, shared network, CPE server 1.10.2).

I can reproduce your previous error (the `PermissionError` stuff) if the name is configured on PalmOS and the hotsync manager does not reply: PalmOS then tries to IP broadcast, and this is not allowed for ordinary users.

Your debug log looks OK, too --- it opens a socket that targets the hotsync manager and then waits until it can send (that's the `select` part). Again, it seems like your hotsync manager does not reply. Are you sure hotsync manager is running, network hotsync is enabled in the manager settings, and that no Windows firewall is blocking the connection?

**Comment by danbae56** [comment]
You were once again right, HotSync Manager was blocked by the Windows firewall. Seems very strange to me – I have never tinkered with the firewall settings in Windows before, so some other process must have introduced the blocking after I moved. Overall, quite a lot more fiddling to get the connection set up this time around. But now I managed to perform HotSync at last! Many thanks once again!

**Comment by DirtyHairy** [comment]
You're very welcome 😏
