### ISSUE TITLE
After hotsync has finished, there are  no PIM information synced.

### ISSUE THREAD

**Issue by tatbestand216** [cloudpilot-emu/cloudpilot-emu#66]
Hello ,
I have hotsynced my cloudpilot (with M515 rom, browers is chrome) via network,the hotsync showed hotsyncing  is success. 
It showed "memopad--ok, datebook--ok...", and so on.
But when I want to check the information in my cloudpilot, there is nothing.
Does anyone have the same problem?
Cloudpilot is a very nice project, that I could revist the great palm os.

**Comment by DirtyHairy** [comment]
Thanks for the compliment 😏 What software are you hotsyncing against? Palm Desktop?

**Comment by tatbestand216** [comment]
I use palmdesktop.
After using safari , the PIM information has shown. 
That is great!

**Comment by DirtyHairy** [comment]
Glad it works! The choice of browser can't have anything to with it, though, hotsync is handled by PalmOS itself, the only part taken over by CloudplotEmu is the network communication. I have, however, seen similar issues with Palm Desktop running on modern Windows in the past. It expects to be run with administrative permissions, and there is a patch somewhere on Palm Desktop that is required to sync "legacy" PalmOS versions reliably (I think OS < 5 counts as legacy here): https://palmdb.net/app/palm-desktop

**Comment by tatbestand216** [comment]
sorry，there is still no information in my pim software.
Maybe I didn't know how to set it up.
Does anyone know how to hotsync PIM informatoon ?
Thank you very much.

**Comment by DirtyHairy** [comment]
Have you checked and installed the patch on PalmDB that I mentioned (https://palmdb.net/content/files/tools-desktop/palm-desktop/LegacyHSFix.zip)? I suspect that it will solve your issue.

**Comment by tatbestand216** [comment]
Thank for your replied.
I have installed this patch,but it still cannot sync PIM information.
But I choose install .prc file through palmdesketop,it installed files succeed.
When I start hotsync server on my PC .
It showed two error message,winerror 10022 and winerror 10049,is that the reason ?
But it still hotsynced through network,and finished hotsync.
I sincerely thank your help.
Thank you very much.

**Comment by DirtyHairy** [comment]
Hm, have you tried running Palm Desktop as administrator?

**Comment by tatbestand216** [comment]
Thanks for your replied,I tried runnin Palm Desktop as administrator . And use Palm Desktop as PIM app(not outlook,it has ie5setup.exe problem),there is still no PIM Information .
Is there anything that I have not think about?

**Comment by DirtyHairy** [comment]
Mmh, no, that should work. If you enter a note in Palm Desktop, does it show up on PalmOS? If you enter a new note in PalmOS, does it show up in Palm Desktop?

You could head over to the palmdb discord and ask there, chances are that someone will have seen your issue and can help you better than I can.

**Comment by tatbestand216** [comment]
Thank you.I will go to there to ask my question.
Thanks for your replied.

**Comment by DirtyHairy** [comment]
Well, me again, but I replied over there 😏
