### ISSUE TITLE
Can't get emu to connect to local server

### ISSUE THREAD

**Issue by markaudacity** [cloudpilot-emu/cloudpilot-emu#67]
When I start the server, it reports "======== Running on https://0.0.0.0:8667 ========", which AFAIK is not a valid IP address to do anything with. I generated the cert with 127.0.0.1,localhost, but neither 127.0.0.1:8667 nor 0.0.0.0:8667 work when entered as proxy addresses in Settings.

**Comment by markaudacity** [comment]
Entering the proxy server as localhost instead of 127.0.0.1 fixed it.

**Comment by DirtyHairy** [comment]
Weird. Both `127.0.0.1` and `localhost` should work fine (provided they are configured in the certificate), CPE does not do anything fancy beyond building a full URL.

`0.0.0.0` is not a valid address to connect to, but it is a valid listen address --- it means "listen on all IPs / interfaces" 😏
