### ISSUE TITLE
How do i run cloudpilot offline mode without internet

### ISSUE THREAD

**Issue by bishalghimire007** [cloudpilot-emu/cloudpilot-emu#68]
I want to run cloudpilot offline mode but i don't see step by step guide...Need help

**Comment by DirtyHairy** [comment]
You need to load the page with an online connection once. After that (once you can read "app cached for offline use" at the bottom of the about page) the page does not require an internet connection anymore to load and work.

**Comment by DirtyHairy** [comment]
Well, if you want to run CloudpilotEmu on an airgapped machine then you'll have to serve it with a web server there (i.e. `python -m http`. You can either take the build that is served on github.io from the [repository](https://github.com/cloudpilot-emu/cloudpilot-emu.github.io) or build it yourself. 

As an alternative, you can build the native version of CPE and run that, no browser or network required. However, the native build is less comfortable to use and lacks several features.
