### ISSUE TITLE
how do I get data from my actual Palm device into the emulator ?

### ISSUE THREAD

**Issue by JohnGEyles** [cloudpilot-emu/cloudpilot-emu#72]
I've got CloudPilot working on my Android Pixel, but I have no clue how to get the data from my _real_ Palm Vx into the emulator.  I've Hotsync'd it on an old Windows machine to get the backup files - they have .dat extensions and if I try to import them into the emulator it fails.   Apparently it wants to see dot-pdb files (because that's what it produces when I do "Save Backup" and it can happily import those).

I'd be happy to do my backups that way, with the dot-pdb files.  But that doesn't help me get my existing dot-dat files into the emulator.

Do I have to get the networked Hotsync'ign working in order to accomplish this ?

**Comment by DirtyHairy** [comment]
Hi John!

This is slightly tricky. .pdb / .prc is the default serialisation format for PalmOS databases, and PalmOS itself uses it when exporting and importing databases. Unfortunately, Palm Desktop insists of storing PIM data in its own, propietary database format instead (while other databases **are** backed up as .pdb / .prc).

There are essentially two things that you can do to get those databases from a device without a SD card slot:

* Setup network hotsync via the proxy and hotsync the virtual palm with your profile in Palm Desktop just like a real device. You can either do that directly with your pixel, or with a desktop computer and export the databases from there. Just make a backup of your Palm Desktop data directory beforehand as Palm Desktop is not designed to sync a single profile with multiple devices, just in case you end up accidentally overwriting the date on one device with that on the other.

* Use `pilot-xfer` (from pilot-link) on a Linux machine to backup all databases as .prc / .pdb files. A linux VM will do fine of you forward your serial port to the VM.

**Comment by JohnGEyles** [comment]
Ok, thanks.  No access to a Linux machine, so I guess I'll see if I can set up the network Hotsync'ing (looks tricky).

**Comment by JohnGEyles** [comment]
I'm sorry, just not that sopjhisticated a user.   Trying to follow instrcutions for setting up network Hotsync.  Do I start with cloudpilot-server or cloudpilot-emu-embedded ?  Or both ?   Thanks.

**Comment by DirtyHairy** [comment]
All fine, we'll get it working 😏 Setting up the proxy is not hard, but it can be a bit quirky as it requires you to deal with certificates and the IP addresses of the involved machines.

You only need the `cloudpilot-server` download that matches your OS. `cloudpilot-emu-embedded` is something different entirely. Try to follow the networking documentation closely, and feel free to ask me for help if you get stuck.

**Comment by JohnGEyles** [comment]
Thanks.   So I generated the two certificates.   Do I understand correctly that the dot-pem one goes on the Macbook where I installed cloudpilot-server, and the dot-cer one on the Android phone where I'm running the emulator ?  And that it doesn't matter what name I gave the certifictes ?

**Comment by DirtyHairy** [comment]
Precisely. The .pem is the server certificate that is used by the proxy to secure the HTTPS connection (it needs to speak HTTPS as CloudpilotEmu is served via HTTPS, too), and the .cer is the generated root certificate that was used to sign it. The root certificate needs to be installed and trusted on the devices that run CloudpilotEmu (your Android phone).

The name of the certificate is not important; the possible names and IPs that you specify for the server are stored in the SAN (Subject Alternate Name) field of the certificate. The only important thing is that one of those names and IPs matches the address that CloudpilotEmu uses to connect to the proxy; otherwise the browser will not allow the connection.

**Comment by JohnGEyles** [comment]
Ok, installed in Macbook keychain successfully.   Put the root certificate (<name>-root.cer) in google-drive, so can access it on phone.  When I got to "Install a Certificate" doesn't matter if I choose "VPN & app user certificate" or "CA certificate" or "Wifi certificate" - it is grayed out.   Tried downloading the certificate, and for some reason can't even see it from within settings.

**Comment by DirtyHairy** [comment]
OK, this is weird. I just tried on a Pixel 8 on Browserstack (Android 14) and could install the certificate fine. I put my cert in Downloads, then went to Setting -> Security and Privacy -> More Security and Privacy -> Encryption and Credentials -> Instal a certificate -> CA certificate . I selected the certificate and it installed fine --- it displays under "Trusted Credentials -> User" after that.

What name did you assign to the certificate? Maybe there are some weird characters in there that Android does not like. What Pixel and Android version are you using? Could you send me your root certificate via mail? You can find my mail [this file](https://github.com/cloudpilot-emu/cloudpilot-emu/blob/af1bc5945a7d2ccc9a2d1464ce9803d918e2c91c/web/package.json#L4) (line 4). The key has been discarded, so I can't do anything sneaky with it 😏

**Comment by JohnGEyles** [comment]
I just realized Palm Desktop doesn't run on MacOS anymore, so I need to start over using the old Windows machine I was using for Hotsync.   But I imagine I'll have the same difficulty installing the certificate on the Pixel.   Tomorrow ...

**Comment by DirtyHairy** [comment]
Thanks for the certificate! I wonder whether the underscore in the common name may be an issue for android, although I can't realistically imagine it should. I'll try in an emulator later today. Is this your private phone, or is this part of a central device management? Do you have some other security solution running on it that might interfere with the installation of certificates?

You don't have to run the proxy on the same computer that runs Palm Desktop, as long as the computer running the proxy can connect to the other machine.

Technically, if the pixel continues to give you trouble, you can also just set up a virtual device on your Mac, hotsync it, backup the databases from CloudpilotEmu and install them directly on your Pixel. I'm curious to find out what's going on, though 😏

**Comment by JohnGEyles** [comment]
Private phone.   I tried again with a certificate name without underscore in it, and no difference.

**Comment by DirtyHairy** [comment]
I must admit that I am slightly out of ideas then. I can install your root cert just fine in an emulator with Android 14 --- "Install a Certificate" -> "CA Certificate" -> "Install Anyway" , and then the file browser opens, I can go to "Downloads", select the certificate, and it gets installed.

As for plan B: you need the root certificate (the `.cer`) installed and trusted in your Mac keychain (as described in the documentation and as I gather you already did), and you need to pass the server certificate (the `.pem`) to the proxy when you start it on your Mac. You can then enter "localhost" as "Proxy server" in CloudpilotEmu running on your Mac (in Safari or whatever browser you prefer) and hit "Test". Once that works you can move on to setup network hotsync. You just need to be sure that the IP of your Windows machine is accessible from your Mac, and that no Windows firewall is blocking the connection..

**Comment by JohnGEyles** [comment]
Sorry, but what does "pass the server certificate (the .pem) to the proxy when you start it on your Mac" mean ?    Put it on the Windows machine running Hotsync ?

**Comment by JohnGEyles** [comment]
I don't think I can run the server on my Windows machine, because it's not 64-bit.

**Comment by JohnGEyles** [comment]
Thanks for trying.   I'm too stupid to do this.  I tried to install a Linux VM on my Mac, but that didn't go well either.

**Comment by DirtyHairy** [comment]
No, you're not stupid 😏 

> Sorry, but what does "pass the server certificate (the .pem) to the proxy when you start it on your Mac" mean ? Put it on the Windows machine running Hotsync ?

No. Check [this part](https://github.com/cloudpilot-emu/cloudpilot-emu/blob/master/doc/networking.md#start-the-server) of the documentation. You give the path to the certificate as a command line argument to the proxy.

> I don't think I can run the server on my Windows machine, because it's not 64-bit.

You don't have to. The proxy server can happily run on your Mac. CloudpilotEmu connects to the proxy server (running on your Mac) and tells it where PalmOS wants to connect, and the proxy server then forwards the connection to your windows machine.

Just download the proxy for Mac, execute the command in the release description in order to remove it from quarantine and run it with the path to the `.cer` as described in the documentation.

**Comment by JohnGEyles** [comment]
Yeah, I already ran the proxy server on the Mac (but it's with the .prm file, not the .cer file, right ?). I made a virtual Pilot on that Mac too; can't get it to work yet though.    So if I can figure this out, how do I forward the connection to Windows box ?

**Comment by DirtyHairy** [comment]
> But when I test "host integration" (in settings screen for sessions) it says "connections to proxy successful".

That's great, biggest hurdle taken.

The errors that you get are because you misconfigured hotsync. "Name" should be left blank, "Address" should be the IP of your windows machine (since that's where Palm Desktop is running and waiting for connections, not localhost!), and subnet should be set accordingly (most likely 255.255.255.0). You also need to make sure that hotsync is configured to accept TCP/IP connections on your windows machine.

A few errors on the terminal are expected even once you get it working and just part of how hotsync works.

**Comment by JohnGEyles** [comment]
Ok thanks.  I assume you're talking about settings in "primary PC setup" ?

**Comment by DirtyHairy** [comment]
Indeed, seems your virtual Pilot cannot connect to the windows machine through the proxy; the connection to the proxy itself is fine. Do you have a firewall set up on your windows machine? Have you enabled TCP/IP connections in Hotsync (check the screenshot below)?

What are the IPs of your Mac and of your Windows machine, and what did you enter as netmask? Can you start the proxy with an additional parameter `--log debug` and paste the output?

<img width="635" alt="image" src="https://github.com/user-attachments/assets/5b4f385a-b09f-4ff3-9903-0a7f720bf37b">

**Comment by JohnGEyles** [comment]
Here's the debug output from the proxy (these lines repeated ad infinitum):

```
cloudpilot-server:WARNING: 2024-11-21 13:27:08,845: failed to send: BrokenPipeError: [Errno 32] Broken pipe
cloudpilot-server:DEBUG: 2024-11-21 13:27:08,845: select width=3 readFDs=[2] writeFDs=[1] exceptFDs=[] timeout=2000
cloudpilot-server:DEBUG: 2024-11-21 13:27:08,845: socketSendRequest: handle=1 len=28 flags=0 timeout=2000 
cloudpilot-server:DEBUG: 2024-11-21 13:27:08,845: 
00000000: 01 FF 00 00 00 16 90 01  00 00 00 00 00 00 00 20  ............... 
00000010: 00 00 00 08 02 00 00 00  00 00 00 00              ............
```

**Comment by JohnGEyles** [comment]
Firewall appears turned off on the Windows machine.  

My Hotsync screen looks nothing like the one you posted (even with the German).  Mine has a pulldown for Hotsync (within Palm Desktop), and I select Setup.   There are 4 tabs there, one of which is "Network" and that looks right.   No way to enable/disable that I can tell.

**Comment by DirtyHairy** [comment]
It's somewhat hidden. Right click on the hotsync icon in the systray and choose "Settings". You'll end up with the hotsync manager settings, which is the dialog from my screenshot. Choose "Connection" at the left-hand navigation, then enable TCP/IP

**Comment by JohnGEyles** [comment]
There's no Hotsync icon in the systray.    Just a pulldown tab in Palm Desktop, that I described above, where I selected Setupo and there was a tab called Network with a button called TCP/IP setttings.

**Comment by JohnGEyles** [comment]
Just noticed, the debug output from proxy has these lines before the endlessly-repeating set I posted above:

```
cloudpilot-server:INFO: 2024-11-21 14:17:44,158: issued token, lifetime 10 seconds
cloudpilot-server:INFO: 2024-11-21 14:17:44,173: starting proxy connection 0
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,195: socketOpenRequest: type=1 protocol=0
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,197: socketOptionSet handle=1 level=65535 option=8192 value=1 timeout=2000
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,198: socketAddrRequest: handle=1 requestAddressLocal=True requestAddressRemote=False timeout=-1
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,198: socketBindRequest: handle=1 address=('0.0.0.0', 0) timeout=-1
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,199: socketOpenRequest: type=2 protocol=0
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,199: socketOptionSet handle=2 level=65535 option=8192 value=1 timeout=2000
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,200: socketConnectRequest handle=1 address=('192.168.50.12', 14238) timeout=90000
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,200: select width=2 readFDs=[] writeFDs=[1] exceptFDs=[1] timeout=500
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,288: socketSendRequest: handle=1 len=28 flags=0 timeout=2000 
cloudpilot-server:DEBUG: 2024-11-21 14:17:44,288:

```

**Comment by JohnGEyles** [comment]
When I run "nc: connectx to 192.168.50.12 port 14238" from Terminal on Mac, I get:

`nc: connectx to 192.168.50.12 port 14238 (tcp) failed: Connection refused
`

**Comment by DirtyHairy** [comment]
OK, that's your issue there, you cannot connect. Either network hotsync is not enabled, or a firewall is blocking the connection.

**Comment by JohnGEyles** [comment]
I guess it's Firewall on the Windows machine ?   It appears to be turned off, but there are a bunch of very confusing dropdowns there, labeled "Exceptions" and "Advanced".

**Comment by DirtyHairy** [comment]
Very much possible, but I cannot say for sure. What version of windows are you using, and what version of Palm Desktop?

**Comment by DirtyHairy** [comment]
Oh, and can you check your Mac's IP? If you're using Wifi you can find it by option-clicking on the wifi symbol.

**Comment by JohnGEyles** [comment]
192.168.50.247

**Comment by JohnGEyles** [comment]
Windows XP Professional

**Comment by JohnGEyles** [comment]
I believe Palm Desktop is v2.6.3 for Mac.

**Comment by DirtyHairy** [comment]
Ah, wait, I thought you are connecting to Palm Desktop running on Windows, aren't you?

**Comment by JohnGEyles** [comment]
My bad, it's v4.0.1 for Windows

**Comment by DirtyHairy** [comment]
I must admit I am stumped. Your issue definitely is the connection to Palm Desktop, but I can't think of any further (easy) way to diagnose the issue) I am using a Windows 11 VM and Palm Desktop 6.2.2, so I can't replicate your setup. I'll try to setup a XP VM, but'll that take a bit.

**Comment by JohnGEyles** [comment]
I'm still confused why you don't just think it's the connection to the Windows machine (and not necessarily with Palm Desktop) that's the issue.   The test you gave me "nc -v 192.168.50.12 14238" doesn't have anything to do with Palm Desktop, does it, isn't it just pinging the Windows machine ?

**Comment by DirtyHairy** [comment]
Yes it does 😏 Palm Desktop listens on Port 14238 for incoming connections. This command tries to open a connection to port 14238, just like a Pilot. If Palm Desktop were listening (and reachable), then the connection would open and Palm Desktop would start waiting for data.

**Comment by DirtyHairy** [comment]
Best of luck, don't electrocute yourself 😏 Talk to you later!

**Comment by DirtyHairy** [comment]
For the record, before I go afk for today, too: I just setup XP professional in a VM and installed Palm Desktop 4.1.0. I can hotsync successfully, but the interface is slightly different.

* Hotsync manager has to be running, and it does show an icon in the systray when it is up. However, you can control its startup in the Palm Desktop settings (HotSync -> Setup...) --- it can be set to autostart, only when Palm Desktop is running and manual
* Clicking on the hotsync symbol in the tray will pop up a menu. There different connection options can be checked at the top of the menu. Make sure that "Network" is checked (just like in my screenshot below)
* Make sure that Windows Firewall is either off or has an exception set for Hotsync Manager

<img width="244" alt="image" src="https://github.com/user-attachments/assets/8a46f212-d5ee-4367-bca0-8bbb7c036696">

**Comment by JohnGEyles** [comment]
So Hotsync'd my _real_ Pilot to the Windows machine (using the cradle), and then did a Hotsync ("desktop overrides handheld") to the virtual Pilot on my Macbook.   Worked like a charm.   Then did a "save backup" on the virtual Pilot, which created a big ZIP archive, which I can get onto my Android using google-drive, and then upload those files to it (in fact, I could just upload the ZIP archive and get everything in one step, thanks !)

So if I'm happy with the virtual Pilot on my PIxel as an alternative to the real device, I can just do my backups with "save to backup" and any restores (if need be) using the method I just used to get the data only my Pixel Pilot just now.

Couple final questions: where do virtual Pilots (on Macbook and on Pixel) save their data (other than if you do a save-to-backup) ?   And have you used the plastic Pilot stylus on a virtual Pilot on your phone much, and if so, how does the phone's screen hold up (does it get scratched) ?

Finally, thank you SO much for creating this emulator.   As you know, the Palm hardware is crap, and I was tired of having to buy units off eBay and hope they worked awhile.   And, of course, thanks for your patience is helping me to get this to work.

**Comment by JohnGEyles** [comment]
> > And have you used the plastic Pilot stylus on a virtual Pilot on your phone much, and if so, how does the phone's screen hold up (does it get scratched) ?
> 
> I am afraid no, I just use my fingers 😏

Actually, I dunno if all phones are like this, but nothing other than my finger works.   Tried a Palm stylus and a q-tip (ear swab), and nothing.   I guess it sense the heat.

**Comment by DirtyHairy** [comment]
Nah, it is a [capacitive screen](https://en.wikipedia.org/wiki/Capacitive_sensing) 😏  All modern touch screens work like this. They are less accurate than the resistive screen of the Palm, but they are more robust, don't require calibration and, most important, they support multitouch.

There a special pens that have a conductive tip and that work on capacitive touch screen.s

**Comment by JohnGEyles** [comment]
Excellent, I'll buy one. Thanks.

Are you going to market this ?   I imagine I'm not the only Palm user who'd like to keep using their excellent GUI, but tired of their inferior hardware.

**Comment by DirtyHairy** [comment]
Nah, this is open source, and the core is still POSE, even though heavily modified and extended --- it wouldn't feel right to try to make money of it. Sometimes I receive a donation, but this is just a hobby that allows me to relax in the evening: preserving the platform, challenge and learning. And if people use and like it that tickles my ego, too 😏

**Comment by JohnGEyles** [comment]
Christian, Happy New Year.   I'd like to make a small donation.  How may I do this ?

**Comment by DirtyHairy** [comment]
Hi John!

A happy new year to you, too, and thanks a lot for your kind offer! Please send me an email and I'll send you my paypal.me link. You can find my email address in the code:

https://github.com/cloudpilot-emu/cloudpilot-emu/blob/c0ba1b7b71e7c51164c99643e39a5ec2c04565cf/web/package.json#L4 

Thanks again
    -Christian
